### ISSUE TITLE
Order data is cleared from state too early

### ISSUE THREAD

**Issue by juho-jaakkola** [AbsoluteWebServices/vsf-amazon-pay#2]
IMO the `RESET_ORDER` mutation is called too early within the order process:

https://github.com/AbsoluteWebServices/vsf-amazon-pay/blob/ef4d4a68a473d81ae37817bd8eb196f7b5b8344c/hooks/afterRegistration.ts#L128

My use case is that I need to save the Magento 2 order increment ID into the transaction saved in Amazon Pay to be able to track it easily later.

Magento does not provide this ID until the checkout has been finished. However, by this time the Amazon Reference ID has already been cleared from the Vuex state, so I cannot do the needed additional Amazon API call anymore.

**Comment by dmitry-kozachek** [comment]
@juho-jaakkola Hi, first of all I need to say, we refused to use Amazon Pay in our project, so this module isn't tested.
This module implements only part of the Amazon Pay order processing, there should be server side Magento extension wich will handle other part.
For the reference:
https://m.media-amazon.com/images/G/03/AMZNPayments/IntegrationGuide/AmazonPay_-_Order_Confirm_And_Omnichronous_Authorization_Including-IPN-Handler._V516642695_.svg?ld=APUSLPADirect

My notes here:
![amazonpay_order_confirm_and_omnichronous_authorization_including-ipn-handler](https://user-images.githubusercontent.com/10741400/78640552-a2457d00-78b8-11ea-9d68-3bfb319fa89f.jpg)

**Comment by juho-jaakkola** [comment]
Ok, thanks for taking the time to reply and provide the graph. I'll have to review how to proceed with the Amazon integration.
